### ISSUE TITLE
Walrus operator and parenthesis

### ISSUE THREAD

**Issue by selasley** [CodeMouse92/DeadSimplePython#1]
I enjoyed your interview on the TalkPython podcast so I bought the book.  Listing 3-24 contains the code

```
if (eggs := 7 + 5) == 12:
    print("We have one dozen eggs")
print(eggs)  # prints 12
```

followed by the statement "The assignment expression is enclosed in parentheses for readability, although I technically could have omitted them."  If you omit the parentheses then print(eggs) will print True (from 7 + 5 == 12) instead of 12.  Tested with python 3.9.16 and 3.11.3.  I've caused bugs in my code by omitting parenthesis around the walrus operator.

Thanks for writing the book.

**Comment by szczerski** [comment]
You're right. 
The interesting thing is that you don't necessarily have to choose whether you want the Boolean result of the comparison `7 + 5 == 12` or just the sum of 7 and 5 `if (eggs := 7 + 5) == 12`, but you can also assign only the first variable 
`if (eggs := 7) + 5 == 12  # and now eggs has a value of 7`
By contrast, with the ternary operator, parentheses are required
`print(f"We have one dozen ({eggs} eggs)" if (eggs := 7 + 53) == 12 else f"We have {eggs} eggs")  # We have 60 eggs`

**Comment by CodeMouse92** [comment]
Thanks for finding this! Good catch.

**Comment by CodeMouse92** [comment]
The book is going to reprint, and I've asked the publisher to include this correction. Thank you!
