### ISSUE TITLE
Misc feedback

### ISSUE THREAD

**Issue by paulfloyd** [CodeMouse92/DeadSimplePython#2]
P 224 I don't think that Counter is the equivalent of multiset. In general multisets are containers that can have more than one element per key rather than a count per key.

P 47 first block example the code says "foo %= 51" but the comment says "144.0 % 15" - the comment should contain "% 51" as well

P 47 again I don't see anything saying whether right shift is arithmetic (preserves sign) or logical (shifts in 0s) - this does get a fair amount of coverage later 

P 51 does 'and' short-circuit?

P 52 I was a bit suprised reading "print(not score == high_score)" - coming from C++ I expected 'not' to have higher precedence than == but that isn't the case in Python

P52 Walrus operator again I found this a bit surprising. Ordinary = can be chained which I'm used to meaning that '=' returns a result that can be read or written to. But it seems Python assignment chaining isn't really chaining which is why the walrus operator is needed.

P 68 what is the difference between literal patterns and REs?

P 151 __init__ - there can only be one

P 153 __new__ as an constructor. Very confusing from a C++ where 'new' is an allocator and the class constructor is the constructor.

P 318 Fig 11-1 the labelling in the image looks wrong to me (and is right in the text). 'Parent' is c:\windows\system and name is python37.dll

P 326 does path.touch() not update the target filestamp?

P 345 some languages do have separate logical and arithmetic shift operators, like >>> and >>

**Comment by CodeMouse92** [comment]
Apologies for the long delay. It's been a bear of a year.

> P 47 first block example the code says "foo %= 51" but the comment says "144.0 % 15" - the comment should contain "% 51" as well

Good catch! Adding this to the book errata.

> P 47 again I don't see anything saying whether right shift is arithmetic (preserves sign) or logical (shifts in 0s) - this does get a fair amount of coverage later

Yes, these are arithmetic shifts. Ideally I could have mentioned that, but I'm glad it's covered sufficiently later. I'll make a note for v2.

> P 51 does 'and' short-circuit?

Yes it does. In v2, I'll mention this.

> P 52 I was a bit suprised reading "print(not score == high_score)" - coming from C++ I expected 'not' to have higher precedence than == but that isn't the case in Python

Python is rather different here, but once you're used to it, it makes reading the code a little easier.

> P52 Walrus operator again I found this a bit surprising. Ordinary = can be chained which I'm used to meaning that '=' returns a result that can be read or written to. But it seems Python assignment chaining isn't really chaining which is why the walrus operator is needed.

Not only that, I made a bit of a mistake. The parentheses are _not_ optional, as they control what is assigned to the walrus operator. "Explicit is better than implicit" was probably the guiding star on not using assignment chaining the way you might expect. It's better to just explicitly specify what should get stored in the variable by using parentheses. I'm adding this fix to the errata.

> P 68 what is the difference between literal patterns and REs?

Under the hood, literal patterns are matched exactly, while regular expressions have a more complex rule set (and are slower as a result).

> P 151 init - there can only be one

If I'm understanding you, _technically_ you can write more than one initializer by utilizing single-dispatch generic functions (pg. 449). I've done it in the wild, and it works spectatularly well.

> P 153 new as an constructor. Very confusing from a C++ where 'new' is an allocator and the class constructor is the constructor.

It can be at first, definitely. Python doesn't give you control over allocation, however, so the lack of a "new" keyword will hopefully help you shift perspectives in Python.

> P 224 I don't think that Counter is the equivalent of multiset. In general multisets are containers that can have more than one element per key rather than a count per key.

I see where I got this confused. In Java, Multisets are used for Counters, but only as a side effect of keeping track of multiple items per key. I'll add this to the errata.

> P 318 Fig 11-1 the labelling in the image looks wrong to me (and is right in the text). 'Parent' is c:\windows\system and name is python37.dll

Narf! Excellent catch, sir! I do not know how that slipped past everyone, but the graphics designer must have introduced that error when they created the new graphics off my sketches.

> P 326 does path.touch() not update the target filestamp?

Oops! Yes, it does.

> P 345 some languages do have separate logical and arithmetic shift operators, like >>> and >>

Good technicality there, thanks.

**Comment by CodeMouse92** [comment]
The book will be going into reprint, and I'll have the publisher include this errata. Thanks!
