### ISSUE TITLE
Listing 3-36 problem

### ISSUE THREAD

**Issue by softwareliberationarmy** [CodeMouse92/DeadSimplePython#3]
I'm really enjoying the book so far, trying to write out by hand as many of the exercises as I can. 

When I attempt to escape the curly braces in a formatted string, though, it does not recognize the variable I'm passing in. Screenshot attached. This is with Python 3.11. Is there something I'm doing wrong or is this a recent change to Python behavior? 

![Listing3-36](https://github.com/CodeMouse92/DeadSimplePython/assets/1095220/f544cff5-77fb-405e-a1cd-6b596fba0c88)

**Comment by softwareliberationarmy** [comment]
UPDATE: this might be an erratum, because when I try three curly braces on each side instead of 2, I get the expected result. So the two curly braces together make one escaped curly brace, and the third curly brace is for the format variable. 

![Listing3-36](https://github.com/CodeMouse92/DeadSimplePython/assets/1095220/2fc05629-1b03-47bb-8fc0-7ac2d0becf0b)

**Comment by CodeMouse92** [comment]
Huh. You are very correct. I don't know how that slipped past me and _six_ editors. Good catch!

**Comment by softwareliberationarmy** [comment]
Editors. Whaddyagonnado? :-)

**Comment by CodeMouse92** [comment]
_Clicks red pen._

> Editors. Wha~d~t [are] y~a~ou ~gonna~going [to] do?

Sorry. Could not resist.

**Comment by CodeMouse92** [comment]
The book is going into reprinting, and we'll be including this correction. Thanks again!
