### ISSUE TITLE
Possible errors in Chapter 15, element_generic example

### ISSUE THREAD

**Issue by kirillmartynov** [CodeMouse92/DeadSimplePython#5]
Hi Jason, 

Thank you for the book! 

I believe there are a couple of possible errors in the following code sample: https://github.com/CodeMouse92/DeadSimplePython/blob/main/Ch15/element_generic.py

1. `if 'C' in formula.keys():` and `if 1 in formula.keys():` in lines 93 and 96 appear incorrect:
    * The first condition with `C` works because `__hash__(self)` is implemented as  `__hash__(element.symbol)` which accidentally is the same value as `hash("C")` changing `def __hash__(self)` to `return hash(self.symbol) + 1` will break this implementation. I don't think such a brittle implementation was intended? 
    * The second condition will fail to find any "H" in the compound. 
  
It seems that is both cases, we want to rely on `__eq__` instead of `__hash__`. Then we need to convert `formula.keys()` into a list, e.g. `if 'C' in list(formula.keys()):`.

2. `@overload` doesn't seem to work as intended – comparison with `float` falls back to the default implementation of __eq__. For example, `print(hydrogen == 1.0)` produces the following error: 
```
Traceback (most recent call last):
  File "/Users/kirill/Programming/toy_python/DeadSimplePython/Ch15/element_generic.py", line 120, in <module>
    print(hydrogen == 1.0)
  File "/Users/kirill/.pyenv/versions/3.10.0/lib/python3.10/functools.py", line 915, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/Users/kirill/Programming/toy_python/DeadSimplePython/Ch15/element_generic.py", line 31, in __eq__
    return self.symbol == other.symbol
AttributeError: 'float' object has no attribute 'symbol'
```

Best,
Kirill

**Comment by CodeMouse92** [comment]
Hi Kirill!

I'll start with (2), as you are _absolutely right_. While `@typing.overload` should work as I describe normally, it doesn't play well with other decorators. That was a major oversight on my part. Thankfully, my publisher is reprinting the book, so we'll get that fixed.

As to (1), you're definitely correct that `if 1 in formula.keys():` fails. That should have checked for `H` instead. Not sure how I overlooked that obvious detail.

As to the concern about the possible brittleness of using `__hash__()` like this, I'm not terribly concerned. I did write the classes to depend on that implementation detail, so the element symbol (guaranteed unique for all real elements entered correctly) is used as the unique identifier. You're correct that it tightly couples Element and Compound, but that's one of those acceptable little compromises to make a sane example. In fact, this is one of my least favorite examples in the book...it took me three weeks to develop, and I was fairly going out of my mind by time I finished it. On the upside, it shows how hashes are _used_, and that makes the compromise a bit valuable in itself.

Thanks for your comments!
