### ISSUE TITLE
Ch20/profiling_with_timeit.py: "count" variable is not used

### ISSUE THREAD

**Issue by sycai** [CodeMouse92/DeadSimplePython#7]
Hey Jason,

Thank you so much for writing this book! It it an enjoyment reading it from cover to cover.

One thing I noticed in your example code [Ch20/profiling_with_timeit.py](https://github.com/CodeMouse92/DeadSimplePython/blob/main/Ch20/profiling_with_timeit.py) is that the variable `count` is defined but not used. This file corresponds to the Listing 20-42 in the book, where you mentioned that "I bound this value, ..., to `count` and passed it to the optional `number=` keyword argument of `timeit`". So I guess you meant `timeit(multiple_assign, number=count)`?

Best,

**Comment by CodeMouse92** [comment]
Yes! Excellent catch! I'll make sure to fix this in the second edition.
